export const categories = [
  { id: 'ac',         name: 'AC repair',          hindi: 'एसी रिपेयर' },
  { id: 'plumbing',   name: 'Plumbing',           hindi: 'नल-पाइप' },
  { id: 'electrical', name: 'Electrical',         hindi: 'बिजली का काम' },
  { id: 'tv',         name: 'TV repair',          hindi: 'टीवी रिपेयर' },
  { id: 'carpenter',  name: 'Carpenter',          hindi: 'बढ़ई' },
  { id: 'painting',   name: 'Painting',           hindi: 'पेंटिंग' },
  { id: 'tiles',      name: 'Tiles & renovation', hindi: 'टाइल्स' },
];

export const societies = [
  { id: 's1', name: 'Sai Krupa CHS',          area: 'Diva East, Thane', type: 'society' },
  { id: 's2', name: 'Shree Ganesh Apartment', area: 'Kopar Khairane',   type: 'society' },
  { id: 's3', name: 'Ambe Nagar',             area: 'Diva Gaon',        type: 'village' },
];

export const workers = [
  // ---------- Sai Krupa CHS ----------
  {
    id: 'w1',
    name: 'Imran Shaikh',
    categoryId: 'ac',
    societyId: 's1',
    phone: '9820041288',
    vouchCount: 11,
    vouchedBy: ['A-304', 'B-108', 'C-402', 'A-101', 'B-205'],
    yearsActive: 9,
    lastCalled: '2 din pehle',
    note: 'Split aur window dono karte hain',
  },
  {
    id: 'w2',
    name: 'Ramesh Yadav',
    categoryId: 'ac',
    societyId: 's1',
    phone: '9820012345',
    vouchCount: 7,
    vouchedBy: ['B-402', 'A-201', 'C-105'],
    yearsActive: 6,
    lastCalled: '5 din pehle',
    note: 'Gas filling aur servicing',
  },
  {
    id: 'w3',
    name: 'Sanjay Pawar',
    categoryId: 'ac',
    societyId: 's1',
    phone: '9820077451',
    vouchCount: 3,
    vouchedBy: ['C-203', 'B-501'],
    yearsActive: 2,
    lastCalled: '3 hafte pehle',
    note: 'Naya hai, rate thoda kam lete hain',
  },
  {
    id: 'w4',
    name: 'Dinesh Vishwakarma',
    categoryId: 'plumbing',
    societyId: 's1',
    phone: '9820033910',
    vouchCount: 14,
    vouchedBy: ['A-201', 'B-402', 'C-301', 'A-105', 'B-104'],
    yearsActive: 12,
    lastCalled: 'kal',
    note: 'Leakage aur bathroom fitting',
  },
  {
    id: 'w5',
    name: 'Ravi Kadam',
    categoryId: 'electrical',
    societyId: 's1',
    phone: '9820056702',
    vouchCount: 9,
    vouchedBy: ['B-205', 'A-304', 'C-402'],
    yearsActive: 7,
    lastCalled: '1 hafta pehle',
    note: 'Wiring, MCB, fan installation',
  },
  {
    id: 'w6',
    name: 'Shabbir Ansari',
    categoryId: 'tv',
    societyId: 's1',
    phone: '9820019834',
    vouchCount: 4,
    vouchedBy: ['A-101', 'C-105'],
    yearsActive: 5,
    lastCalled: '2 hafte pehle',
    note: 'LED panel aur display ka kaam',
  },
  {
    id: 'w7',
    name: 'Mahesh Gaikwad',
    categoryId: 'carpenter',
    societyId: 's1',
    phone: '9820064417',
    vouchCount: 6,
    vouchedBy: ['B-108', 'A-201', 'C-301'],
    yearsActive: 11,
    lastCalled: '4 din pehle',
    note: 'Almirah, door repair, loft',
  },

  // ---------- Shree Ganesh Apartment ----------
  {
    id: 'w8',
    name: 'Arif Qureshi',
    categoryId: 'electrical',
    societyId: 's2',
    phone: '9820088126',
    vouchCount: 12,
    vouchedBy: ['D-702', 'E-304', 'D-201', 'F-101'],
    yearsActive: 10,
    lastCalled: '3 din pehle',
    note: 'Pura building ka wiring kar chuke hain',
  },
  {
    id: 'w9',
    name: 'Sunil Tiwari',
    categoryId: 'plumbing',
    societyId: 's2',
    phone: '9820045573',
    vouchCount: 5,
    vouchedBy: ['E-304', 'D-508'],
    yearsActive: 4,
    lastCalled: '1 hafta pehle',
    note: 'Tanki cleaning bhi karte hain',
  },
  {
    id: 'w10',
    name: 'Prakash Jadhav',
    categoryId: 'painting',
    societyId: 's2',
    phone: '9820071209',
    vouchCount: 8,
    vouchedBy: ['F-101', 'D-702', 'E-205'],
    yearsActive: 8,
    lastCalled: '2 mahine pehle',
    note: 'Ek room ek din me, team ke saath',
  },
  {
    id: 'w11',
    name: 'Bhushan More',
    categoryId: 'tiles',
    societyId: 's2',
    phone: '9820092640',
    vouchCount: 3,
    vouchedBy: ['D-201', 'E-304'],
    yearsActive: 6,
    lastCalled: '1 mahina pehle',
    note: 'Bathroom aur kitchen tiling',
  },
  {
    id: 'w12',
    name: 'Nitin Sawant',
    categoryId: 'ac',
    societyId: 's2',
    phone: '9820038175',
    vouchCount: 6,
    vouchedBy: ['E-205', 'D-508', 'F-101'],
    yearsActive: 5,
    lastCalled: '6 din pehle',
    note: 'AMC bhi karte hain',
  },

  // ---------- Ambe Nagar, Diva Gaon (village) ----------
  {
    id: 'w13',
    name: 'Vitthal Bhoir',
    categoryId: 'electrical',
    societyId: 's3',
    phone: '9820025908',
    vouchCount: 15,
    vouchedBy: ['Patil Wada', 'Shivaji Chowk', 'Bhoir Ali', 'Mandir Road'],
    yearsActive: 18,
    lastCalled: 'kal',
    note: 'Gaon me yahi ek hain, sab inhi ko bulate hain',
  },
  {
    id: 'w14',
    name: 'Ganpat Patil',
    categoryId: 'plumbing',
    societyId: 's3',
    phone: '9820016733',
    vouchCount: 7,
    vouchedBy: ['Shivaji Chowk', 'Patil Wada', 'Nava Ghar'],
    yearsActive: 9,
    lastCalled: '4 din pehle',
    note: 'Borewell aur pump ka kaam bhi',
  },
  {
    id: 'w15',
    name: 'Rajesh Mhatre',
    categoryId: 'carpenter',
    societyId: 's3',
    phone: '9820083461',
    vouchCount: 4,
    vouchedBy: ['Bhoir Ali', 'Mandir Road'],
    yearsActive: 7,
    lastCalled: '2 hafte pehle',
    note: 'Lakdi ka darwaza aur khidki',
  },
];
