export const strings = {
  en: {
    tagline: 'The kaarigar your neighbours have already called',
    society: 'Your society',
    whatWork: 'What needs fixing?',
    back: 'Back',
    call: 'Call',
    vouch: 'I called them',
    neighbours: 'neighbours have called them',
    more: 'more',
    lastCall: 'Last call',
    years: 'years working',
    empty: 'No kaarigar in this society yet',
    emptySub: 'You could be the first — know someone? Add them.',
    modalTitle: 'Did you call them?',
    flatLabel: 'Your flat number',
    flatError: 'Enter your flat number',
    confirm: 'Yes, I called them',
    cancel: 'Cancel',
    countWord: 'kaarigar',
    noCount: 'None yet',
    flatPlaceholder: 'e.g. B-402',
    whatsapp: 'WhatsApp',
    whatsappReady: 'WhatsApp is opening — message is ready, just hit send',
  },
  hinglish: {
    tagline: 'Wo kaarigar jise aapke padosi bula chuke hain',
    society: 'Aapki society',
    whatWork: 'Kya kaam hai?',
    back: 'Wapas',
    call: 'Call karo',
    vouch: 'Maine bulaya tha',
    neighbours: 'पड़ोसियों ने बुलाया है',
    more: 'aur',
    lastCall: 'Last call',
    years: 'saal se',
    empty: 'Is society me abhi koi kaarigar nahi hai',
    emptySub: 'Aap pehle ho sakte ho — kisi ko jaante ho to add karo',
    modalTitle: 'Aapne inhe bulaya tha?',
    flatLabel: 'Aapka flat number',
    flatError: 'Flat number daal do',
    confirm: 'Haan, maine bulaya tha',
    cancel: 'Rehne do',
    countWord: 'kaarigar',
    noCount: 'Abhi koi nahi',
    flatPlaceholder: 'Jaise B-402',
    whatsapp: 'WhatsApp',
    whatsappReady: 'WhatsApp khul raha hai — message ready hai, bas send dabao',
  },
  hindi: {
    tagline: 'वो कारीगर जिसे आपके पड़ोसी बुला चुके हैं',
    society: 'आपकी सोसाइटी',
    whatWork: 'क्या काम है?',
    back: 'वापस',
    call: 'कॉल करो',
    vouch: 'मैंने बुलाया था',
    neighbours: 'पड़ोसियों ने बुलाया है',
    more: 'और',
    lastCall: 'आखिरी कॉल',
    years: 'साल से',
    empty: 'इस सोसाइटी में अभी कोई कारीगर नहीं है',
    emptySub: 'आप पहले हो सकते हो — किसी को जानते हो तो जोड़ो',
    modalTitle: 'आपने इन्हें बुलाया था?',
    flatLabel: 'आपका फ्लैट नंबर',
    flatError: 'फ्लैट नंबर डालो',
    confirm: 'हाँ, मैंने बुलाया था',
    cancel: 'रहने दो',
    countWord: 'कारीगर',
    noCount: 'अभी कोई नहीं',
    flatPlaceholder: 'जैसे B-402',
    whatsapp: 'WhatsApp',
    whatsappReady: 'WhatsApp खुल रहा है — मैसेज तैयार है, बस भेजो दबाओ',
  },
}

export function whatsappMessage({ worker, society, category }) {
  return `नमस्ते ${worker.name} जी, मैं ${society.name} से हूँ। आपका नंबर Kaarigar ऐप पर मिला — हमारी सोसाइटी के ${worker.vouchCount} लोग आपको बुला चुके हैं। ${category.hindi} का काम है, कब आ सकते हैं?`
}