export const strings = {
  en: {
    title: 'Kaarigar',
    themeLight: 'Light',
    themeDark: 'Dark',
    tagline: 'The kaarigar your neighbours have already called',
    society: 'Your society',
    whatWork: 'What needs fixing?',
    back: 'Back',
    call: 'Call',
    vouch: 'I called them',
    neighbours: 'neighbours have called them',
    morePrefix: 'and',
    moreSuffix: 'more',
    lastCall: 'Last call',
    years: 'years working',
    empty: 'No kaarigar in this society yet',
    emptySub: 'You could be the first — know someone? Add them.',
    modalTitle: 'Did you call them?',
    flatLabel: 'Your flat number',
    flatError: 'Enter your flat number',
    confirm: 'Yes, I called them',
    cancel: 'Cancel',
    countWord: 'kaarigar',
    noCount: 'None yet',
    flatPlaceholder: 'e.g. B-402',
    whatsapp: 'WhatsApp',
    whatsappReady: 'WhatsApp is opening — message is ready, just hit send',
    locateBtn: 'Find me by location',
    locateBusy: 'Searching...',
    locateError: 'Location not found — pick from the list',
    kmAway: 'km away',
    addressLabel: 'Your address',
    addressPlaceholder: 'Or type your address — e.g. Sector 4, Kopar Khairane',
    addressBtn: 'Find',
    addressFoundWord: 'found',
    addressNotFound: "This area isn't in the list yet — you could be the first.",
    pitchHeadline:
      "When the AC breaks, you don't open Google. You ask the neighbour.",
    pitchBody:
      "Every society has one person whose electrician becomes everyone's electrician. That network already exists — it's just not written down anywhere. Kaarigar writes it down.",
    pitchCommission: 'Commission',
    pitchApp: 'App for the kaarigar',
    pitchSocieties: 'Societies live',
    pitchTeam: 'Team CoDeOn',
  },
  hinglish: {
    title: 'Kaarigar',
    themeLight: 'Light',
    themeDark: 'Dark',
    tagline: 'Wo kaarigar jise aapke padosi bula chuke hain',
    society: 'Aapki society',
    whatWork: 'Kya kaam hai?',
    back: 'Wapas',
    call: 'Call karo',
    vouch: 'Maine bulaya tha',
    neighbours: 'पड़ोसियों ने बुलाया है',
    morePrefix: 'aur',
    moreSuffix: 'aur',
    lastCall: 'Last call',
    years: 'saal se',
    empty: 'Is society me abhi koi kaarigar nahi hai',
    emptySub: 'Aap pehle ho sakte ho — kisi ko jaante ho to add karo',
    modalTitle: 'Aapne inhe bulaya tha?',
    flatLabel: 'Aapka flat number',
    flatError: 'Flat number daal do',
    confirm: 'Haan, maine bulaya tha',
    cancel: 'Rehne do',
    countWord: 'kaarigar',
    noCount: 'Abhi koi nahi',
    flatPlaceholder: 'Jaise B-402',
    whatsapp: 'WhatsApp',
    whatsappReady: 'WhatsApp khul raha hai — message ready hai, bas send dabao',
    locateBtn: 'Meri location se dhundho',
    locateBusy: 'Dhundh rahe hain...',
    locateError: 'Location nahi mili — list se chun lo',
    kmAway: 'km door',
    addressLabel: 'Aapka address',
    addressPlaceholder: 'Ya apna address likho — jaise Sector 4, Kopar Khairane',
    addressBtn: 'Dhundho',
    addressFoundWord: 'mila',
    addressNotFound: 'Ye area abhi list me nahi hai — aap pehle ho sakte ho.',
    pitchHeadline:
      'Jab AC kharab hota hai, aap Google nahi kholte. Padosi se poochte ho.',
    pitchBody:
      'Har society me ek banda hai jiska electrician sabka electrician ban jata hai. Ye network pehle se hai — bas kahin likha nahi hai. Kaarigar usko likh deta hai.',
    pitchCommission: 'Commission',
    pitchApp: 'App kaarigar ke liye',
    pitchSocieties: 'Societies live',
    pitchTeam: 'Team CoDeOn',
  },
  hindi: {
    title: 'कारीगर',
    themeLight: 'लाइट',
    themeDark: 'डार्क',
    tagline: 'वो कारीगर जिसे आपके पड़ोसी बुला चुके हैं',
    society: 'आपकी सोसाइटी',
    whatWork: 'क्या काम है?',
    back: 'वापस',
    call: 'कॉल करो',
    vouch: 'मैंने बुलाया था',
    neighbours: 'पड़ोसियों ने बुलाया है',
    morePrefix: 'और',
    moreSuffix: 'और',
    lastCall: 'आखिरी कॉल',
    years: 'साल से',
    empty: 'इस सोसाइटी में अभी कोई कारीगर नहीं है',
    emptySub: 'आप पहले हो सकते हो — किसी को जानते हो तो जोड़ो',
    modalTitle: 'आपने इन्हें बुलाया था?',
    flatLabel: 'आपका फ्लैट नंबर',
    flatError: 'फ्लैट नंबर डालो',
    confirm: 'हाँ, मैंने बुलाया था',
    cancel: 'रहने दो',
    countWord: 'कारीगर',
    noCount: 'अभी कोई नहीं',
    flatPlaceholder: 'जैसे B-402',
    whatsapp: 'WhatsApp',
    whatsappReady: 'WhatsApp खुल रहा है — मैसेज तैयार है, बस भेजो दबाओ',
    locateBtn: 'मेरी लोकेशन से ढूंढो',
    locateBusy: 'ढूंढ रहे हैं...',
    locateError: 'लोकेशन नहीं मिली — लिस्ट से चुन लो',
    kmAway: 'किमी दूर',
    addressLabel: 'आपका पता',
    addressPlaceholder: 'या अपना पता लिखो — जैसे सेक्टर 4, कोपर खैरणे',
    addressBtn: 'ढूंढो',
    addressFoundWord: 'मिला',
    addressNotFound: 'ये एरिया अभी लिस्ट में नहीं है — आप पहले हो सकते हो।',
    pitchHeadline:
      'जब एसी खराब होता है, आप गूगल नहीं खोलते। पड़ोसी से पूछते हो।',
    pitchBody:
      'हर सोसाइटी में एक बंदा है जिसका इलेक्ट्रिशियन सबका इलेक्ट्रिशियन बन जाता है। ये नेटवर्क पहले से है — बस कहीं लिखा नहीं है। कारीगर उसे लिख देता है।',
    pitchCommission: 'कमीशन',
    pitchApp: 'ऐप कारीगर के लिए',
    pitchSocieties: 'लाइव सोसाइटी',
    pitchTeam: 'Team CoDeOn',
  },
}

export function whatsappMessage({ worker, society, category }) {
  return `नमस्ते ${worker.name} जी, मैं ${society.name} से हूँ। आपका नंबर Kaarigar ऐप पर मिला — हमारी सोसाइटी के ${worker.vouchCount} लोग आपको बुला चुके हैं। ${category.hindi} का काम है, कब आ सकते हैं?`
}